// Micro-Actions Library
// Daily Sparks - Quick actions for each life area

export interface MicroAction {
  id: string;
  text: string;
  time: string;
  difficulty: "easy" | "medium" | "hard";
  category: string;
  value?: string;
}

export const MICRO_ACTIONS: Record<string, MicroAction[]> = {
  "Relationships": [
    {
      id: "rel-1",
      text: "Send a 'thinking of you' text to someone who matters",
      time: "2 min",
      difficulty: "easy",
      category: "Relationships",
      value: "connection",
    },
    {
      id: "rel-2",
      text: "Give someone a genuine compliment",
      time: "1 min",
      difficulty: "easy",
      category: "Relationships",
      value: "connection",
    },
    {
      id: "rel-3",
      text: "Call someone you haven't talked to in a while",
      time: "10 min",
      difficulty: "medium",
      category: "Relationships",
      value: "connection",
    },
  ],
  "Family": [
    {
      id: "fam-1",
      text: "Send a voice note to a family member sharing appreciation",
      time: "2 min",
      difficulty: "easy",
      category: "Family",
      value: "connection",
    },
    {
      id: "fam-2",
      text: "Set up a regular weekly check-in with family",
      time: "5 min",
      difficulty: "medium",
      category: "Family",
      value: "connection",
    },
    {
      id: "fam-3",
      text: "Do something small to help a family member",
      time: "15 min",
      difficulty: "easy",
      category: "Family",
      value: "contribution",
    },
  ],
  "Career & Purpose": [
    {
      id: "career-1",
      text: "Write down one small goal for this week",
      time: "5 min",
      difficulty: "easy",
      category: "Career & Purpose",
      value: "achievement",
    },
    {
      id: "career-2",
      text: "Learn one new thing about your field",
      time: "10 min",
      difficulty: "easy",
      category: "Career & Purpose",
      value: "growth",
    },
    {
      id: "career-3",
      text: "Update your LinkedIn or portfolio",
      time: "15 min",
      difficulty: "medium",
      category: "Career & Purpose",
      value: "achievement",
    },
  ],
  "Health & Fitness": [
    {
      id: "health-1",
      text: "Do 10 pushups or squats right now",
      time: "2 min",
      difficulty: "easy",
      category: "Health & Fitness",
      value: "vitality",
    },
    {
      id: "health-2",
      text: "Take a 5-minute walk outside",
      time: "5 min",
      difficulty: "easy",
      category: "Health & Fitness",
      value: "vitality",
    },
    {
      id: "health-3",
      text: "Drink a full glass of water",
      time: "1 min",
      difficulty: "easy",
      category: "Health & Fitness",
      value: "vitality",
    },
  ],
  "Nutrition": [
    {
      id: "nutrition-1",
      text: "Eat one serving of vegetables",
      time: "5 min",
      difficulty: "easy",
      category: "Nutrition",
      value: "vitality",
    },
    {
      id: "nutrition-2",
      text: "Drink a glass of water before your next meal",
      time: "1 min",
      difficulty: "easy",
      category: "Nutrition",
      value: "vitality",
    },
    {
      id: "nutrition-3",
      text: "Try a new healthy snack",
      time: "10 min",
      difficulty: "easy",
      category: "Nutrition",
      value: "discovery",
    },
  ],
  "Sleep & Recovery": [
    {
      id: "sleep-1",
      text: "Set a bedtime alarm for tonight",
      time: "1 min",
      difficulty: "easy",
      category: "Sleep & Recovery",
      value: "balance",
    },
    {
      id: "sleep-2",
      text: "Do 5 minutes of evening stretching",
      time: "5 min",
      difficulty: "easy",
      category: "Sleep & Recovery",
      value: "balance",
    },
    {
      id: "sleep-3",
      text: "Put your phone in another room 30 min before bed",
      time: "1 min",
      difficulty: "medium",
      category: "Sleep & Recovery",
      value: "balance",
    },
  ],
  "Hobbies & Play": [
    {
      id: "hobbies-1",
      text: "Spend 10 minutes on a hobby you love",
      time: "10 min",
      difficulty: "easy",
      category: "Hobbies & Play",
      value: "discovery",
    },
    {
      id: "hobbies-2",
      text: "Try something creative you've never done",
      time: "15 min",
      difficulty: "medium",
      category: "Hobbies & Play",
      value: "creativity",
    },
    {
      id: "hobbies-3",
      text: "Play a game or do something purely for fun",
      time: "20 min",
      difficulty: "easy",
      category: "Hobbies & Play",
      value: "discovery",
    },
  ],
  "Learning & Growth": [
    {
      id: "learning-1",
      text: "Read one article or watch one educational video",
      time: "10 min",
      difficulty: "easy",
      category: "Learning & Growth",
      value: "growth",
    },
    {
      id: "learning-2",
      text: "Learn one new word or concept",
      time: "5 min",
      difficulty: "easy",
      category: "Learning & Growth",
      value: "growth",
    },
    {
      id: "learning-3",
      text: "Take an online course lesson",
      time: "20 min",
      difficulty: "medium",
      category: "Learning & Growth",
      value: "growth",
    },
  ],
  "Travel & Experiences": [
    {
      id: "travel-1",
      text: "Visit a place nearby you've never been",
      time: "30 min",
      difficulty: "easy",
      category: "Travel & Experiences",
      value: "discovery",
    },
    {
      id: "travel-2",
      text: "Try a new type of food or cuisine",
      time: "20 min",
      difficulty: "easy",
      category: "Travel & Experiences",
      value: "discovery",
    },
    {
      id: "travel-3",
      text: "Explore a new neighborhood or street",
      time: "15 min",
      difficulty: "easy",
      category: "Travel & Experiences",
      value: "discovery",
    },
  ],
  "Spirituality & Meaning": [
    {
      id: "spirituality-1",
      text: "Spend 5 minutes in quiet reflection",
      time: "5 min",
      difficulty: "easy",
      category: "Spirituality & Meaning",
      value: "meaning",
    },
    {
      id: "spirituality-2",
      text: "Write down one thing you're grateful for",
      time: "2 min",
      difficulty: "easy",
      category: "Spirituality & Meaning",
      value: "meaning",
    },
    {
      id: "spirituality-3",
      text: "Read something inspiring or philosophical",
      time: "10 min",
      difficulty: "easy",
      category: "Spirituality & Meaning",
      value: "meaning",
    },
  ],
  "Finance & Money Mindset": [
    {
      id: "finance-1",
      text: "Review one expense category for this month",
      time: "5 min",
      difficulty: "easy",
      category: "Finance & Money Mindset",
      value: "stability",
    },
    {
      id: "finance-2",
      text: "Set up one automatic savings transfer",
      time: "10 min",
      difficulty: "medium",
      category: "Finance & Money Mindset",
      value: "stability",
    },
    {
      id: "finance-3",
      text: "Learn one money tip or strategy",
      time: "10 min",
      difficulty: "easy",
      category: "Finance & Money Mindset",
      value: "growth",
    },
  ],
  "Community & Contribution": [
    {
      id: "community-1",
      text: "Offer genuine help to one person",
      time: "15 min",
      difficulty: "easy",
      category: "Community & Contribution",
      value: "contribution",
    },
    {
      id: "community-2",
      text: "Find one local cause or organization to support",
      time: "10 min",
      difficulty: "easy",
      category: "Community & Contribution",
      value: "contribution",
    },
    {
      id: "community-3",
      text: "Share something helpful with others",
      time: "5 min",
      difficulty: "easy",
      category: "Community & Contribution",
      value: "contribution",
    },
  ],
};

