export const VALUE_SIGNALS: Record<string, string[]> = {
  honesty: ["honest", "honesty", "truth", "authentic", "real", "genuine", "transparent", "open", "candid"],
  connection: [
    "connect",
    "connection",
    "belong",
    "friends",
    "community",
    "family",
    "relationships",
    "people",
    "social",
    "together",
    "support",
    "love",
    "trust",
    "bond",
    "close",
    "intimate",
  ],
  growth: ["learn", "learning", "growth", "improve", "progress", "develop", "advance", "better", "skill", "knowledge", "education", "study"],
  stability: ["secure", "security", "stability", "safe", "safety", "stable", "consistent", "reliable", "predictable", "steady"],
  discovery: ["new", "explore", "adventure", "travel", "try", "curious", "discover", "experience", "journey", "different", "unknown", "challenge"],
  vitality: [
    "kickboxing",
    "running",
    "weights",
    "yoga",
    "strong",
    "alive",
    "gym",
    "exercise",
    "fitness",
    "health",
    "energy",
    "active",
    "movement",
    "sport",
    "physical",
  ],
  freedom: ["freedom", "autonomy", "independent", "free", "choice", "control", "self", "own", "personal"],
  contribution: ["help", "serve", "community", "give back", "contribute", "volunteer", "support", "assist", "make difference", "impact"],
  meaning: ["meaning", "purpose", "spiritual", "nature", "peace", "fulfillment", "significance", "values", "belief", "important"],
  achievement: ["achievement", "recognition", "career", "promotion", "success", "accomplish", "goal", "ambition", "excel", "win"],
  balance: ["balance", "rest", "sleep", "recovery", "relax", "peaceful", "calm", "harmony", "equilibrium", "wellbeing"],
};

export const VALUE_ICONS: Record<string, string> = {
  honesty: "🧭",
  connection: "🤝",
  growth: "🌱",
  stability: "🛡️",
  discovery: "🔭",
  vitality: "⚡️",
  freedom: "🕊️",
  contribution: "🎁",
  meaning: "✨",
  achievement: "🏆",
  balance: "🌙",
};

// Value-to-Category mapping for insight detection
// Maps values to their related life area categories
export const VALUE_CATEGORY_MAP: Record<string, string[]> = {
  honesty: ["Relationships", "Personal Growth", "Self-Reflection"],
  connection: ["Relationships", "Family", "Social Life", "Community"],
  growth: ["Career", "Learning", "Personal Growth", "Skills Development"],
  stability: ["Finances", "Career", "Home", "Security"],
  discovery: ["Learning", "Travel", "Hobbies", "New Experiences"],
  vitality: ["Health", "Fitness", "Nutrition", "Physical Activity"],
  freedom: ["Lifestyle", "Independence", "Work-Life Balance", "Travel"],
  contribution: ["Community", "Volunteering", "Purpose", "Service"],
  meaning: ["Spirituality", "Purpose", "Self-Reflection", "Values"],
  achievement: ["Career", "Goals", "Accomplishments", "Success"],
  balance: ["Work-Life Balance", "Mental Health", "Rest", "Wellness"],
};

